import Foundation

/// A contextual observation the on-device assistant has made about the
/// customer's home/account state, paired with a natural-language prompt
/// the customer can tap to act on it.
///
/// Signals are generated by `SupportSignalEngine` from
/// `CustomerContext` (equipment health, usage snapshot, managed
/// devices). They're the answer to the exec question "why not just show
/// buttons?" — because the suggestions themselves change based on live
/// state, and the prompts the customer can tap are pre-computed as
/// natural-language strings the LFM will re-parse on its own path. The
/// demo works *both* as a one-tap workflow (for customers who trust
/// the suggestion) and a NLU demonstration (for execs who want to see
/// the model handle ambiguity).
public struct SupportSignal: Identifiable, Equatable, Sendable {
    public enum Domain: String, Sendable { case home, household, billing, service }

    /// Severity drives ordering and color. `.urgent` signals (device
    /// offline, outage detected) surface first. `.info` signals stay
    /// out of the way — they're the plan-fit / optimize-your-setup
    /// tier that's nice-to-have, not must-fix.
    public enum Severity: String, Sendable, CaseIterable {
        case urgent, attention, info

        public var sortKey: Int {
            switch self {
            case .urgent: return 0
            case .attention: return 1
            case .info: return 2
            }
        }
    }

    public let id: String
    public let domain: Domain
    public let severity: Severity
    public let title: String            // "Upstairs extender has been unhealthy for 2 days"
    public let summary: String          // short explainer
    public let suggestedPrompt: String  // what to send if user taps — still run through NLU
    public let suggestedToolID: String? // high-confidence pre-pick (may be nil)
    public let source: String           // e.g. "equipment.extender.status"
    public let icon: String             // SF Symbol name

    public init(
        id: String,
        domain: Domain,
        severity: Severity,
        title: String,
        summary: String,
        suggestedPrompt: String,
        suggestedToolID: String? = nil,
        source: String,
        icon: String
    ) {
        self.id = id
        self.domain = domain
        self.severity = severity
        self.title = title
        self.summary = summary
        self.suggestedPrompt = suggestedPrompt
        self.suggestedToolID = suggestedToolID
        self.source = source
        self.icon = icon
    }
}
