import XCTest
@testable import TelcoTriage

/// Pins the Swift `BM25HierarchyRetriever` to its Python reference
/// (`scripts/telco/retriever.py::BM25HierarchyRetriever`). The golden
/// file is generated by:
///
///     python -m scripts.telco.retriever ...  (see commit history;
///     regenerated whenever the Python retriever changes)
///
/// and lives at `Resources/test_data/retriever_parity_v1.json`.
///
/// We verify TOP-1 page_id parity on every row. Scores aren't pinned
/// (BM25 has small floating-point sensitivity across platforms) but
/// the ordering must be identical.
final class BM25HierarchyRetrieverSwiftParityTests: XCTestCase {
    private struct ParityRow: Decodable {
        let query: String
        let history: [HistoryTurn]
        let top3: [TopHit]
    }
    private struct HistoryTurn: Decodable {
        let role: String
        let body: String
    }
    private struct TopHit: Decodable {
        let page_id: String
        let score: Double
        let link_id: String
        let action_affordance: String?
    }
    private struct ParityFile: Decodable {
        let version: String
        let rows: [ParityRow]
    }

    private var corpus: RAGUnitCorpus!
    private var retriever: BM25HierarchyRetriever!
    private var golden: [ParityRow]!

    override func setUpWithError() throws {
        try super.setUpWithError()
        // RAGUnitCorpus.loadFromBundle's default uses
        // Bundle(for: RAGUnitCorpus.self), which resolves to the main
        // app bundle where rag-units-v1.json is bundled.
        corpus = try RAGUnitCorpus.loadFromBundle()
        retriever = BM25HierarchyRetriever(corpus: corpus)
        // The parity fixture is intentionally NOT bundled into the
        // test target (the test target has no Resources build phase).
        // We resolve it from the source tree via `#filePath` — Apple's
        // sanctioned pattern for source-adjacent test data. Works on
        // simulator because the simulator inherits the host's
        // filesystem. If you move this test file, the relative path
        // below moves with it.
        let testSourcePath = #filePath as NSString
        let fixturePath = testSourcePath.deletingLastPathComponent + "/Fixtures/retriever_parity_v1.json"
        let data = try Data(contentsOf: URL(fileURLWithPath: fixturePath))
        let file = try JSONDecoder().decode(ParityFile.self, from: data)
        golden = file.rows
    }

    func test_top1_pageID_matches_python_reference() {
        var mismatches: [String] = []
        for row in golden {
            let history = row.history.map {
                ConversationTurnSnippet(role: $0.role, body: $0.body)
            }
            let hits = retriever.rank(query: row.query, history: history, k: 3)
            guard let pyTop = row.top3.first else { continue }
            guard let swiftTop = hits.first else {
                mismatches.append("'\(row.query)' — Swift returned no hits (Python top=\(pyTop.page_id))")
                continue
            }
            if swiftTop.pageID != pyTop.page_id {
                mismatches.append(
                    "'\(row.query)' — Swift top=\(swiftTop.pageID) vs Python top=\(pyTop.page_id)"
                )
            }
        }
        XCTAssertTrue(mismatches.isEmpty, "top-1 parity mismatches:\n" + mismatches.joined(separator: "\n"))
    }

    func test_top3_pageIDs_match_python_reference_in_order() {
        var mismatches: [String] = []
        for row in golden {
            let history = row.history.map {
                ConversationTurnSnippet(role: $0.role, body: $0.body)
            }
            let hits = retriever.rank(query: row.query, history: history, k: 3)
            let swiftPIDs = hits.map(\.pageID)
            let pyPIDs = row.top3.map(\.page_id)
            if swiftPIDs != pyPIDs {
                mismatches.append("'\(row.query)' — Swift=\(swiftPIDs) vs Python=\(pyPIDs)")
            }
        }
        XCTAssertTrue(
            mismatches.isEmpty,
            "top-3 page_id ordering mismatches (acceptable up to 2 — investigate if more):\n" +
                mismatches.joined(separator: "\n")
        )
    }

    func test_corpus_loaded_with_expected_size() {
        // Catches accidental corpus-shape regression (e.g. someone
        // overwrote rag-units-v1.json with an older 14-unit dump).
        XCTAssertEqual(corpus.count, 49)
    }

    func test_wifiSpellingVariantsShareOneCanonicalToken() {
        for variant in ["wifi", "Wi-Fi", "Wi‑Fi", "wi fi"] {
            XCTAssertEqual(BM25Tokenizer.tokenize(variant), ["wifi"], variant)
        }
    }

    func test_link_index_covers_known_canonical_pages() {
        let idx = corpus.linkIndex
        XCTAssertNotNil(idx["restart-router"])
        XCTAssertNotNil(idx["network"])
        XCTAssertNotNil(idx["tab-devices"])
        XCTAssertNotNil(idx["home"])
    }

    func test_context_rank_prefers_active_task_when_query_matches_task_step() {
        let context = RetrievalContext(
            priorAssistantText: "To restart router: select the Equipment tile, then select Restart router.",
            priorPageID: "02.07",
            priorLinkID: "restart-router"
        )

        let hits = retriever.rank(query: "Where is the equipment tile", context: context, k: 3)

        XCTAssertEqual(hits.first?.pageID, "02.07")
    }

    func test_context_rank_still_allows_clear_new_topic() {
        let context = RetrievalContext(
            priorAssistantText: nil,
            priorPageID: "02.07",
            priorLinkID: "restart-router"
        )

        let hits = retriever.rank(query: "show me my connected devices", context: context, k: 3)

        XCTAssertEqual(hits.first?.pageID, "04.00")
    }
}
